# Generated by Django 5.1.7 on 2025-03-27 11:21

import homepage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(default=homepage.models.generate_unique_number, editable=False, max_length=10, unique=True, verbose_name='Индивидуальный номер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Заявка создана')),
                ('from_location', models.CharField(max_length=100, verbose_name='Откуда')),
                ('to_location', models.CharField(max_length=100, verbose_name='Куда')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('date', models.DateField(verbose_name='Дата поездки')),
                ('time', models.TimeField(verbose_name='Время поездки')),
                ('num_people', models.PositiveIntegerField(verbose_name='Количество человек')),
                ('luggage', models.PositiveIntegerField(verbose_name='Количество багажа')),
                ('child_seat', models.BooleanField(default=False, verbose_name='Детское кресло')),
                ('pet', models.BooleanField(default=False, verbose_name='Животное')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Статус изменен')),
                ('status', models.CharField(max_length=100, verbose_name='Статус')),
            ],
        ),
    ]
