# Generated by Django 5.1.7 on 2025-03-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за километр')),
                ('price_per_passenger', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за 1 пассажира')),
                ('price_per_baggage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за 1 багаж')),
                ('price_for_pets', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за домашних животных')),
                ('price_for_child_seat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за детское кресло')),
            ],
        ),
    ]
